# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trped_mw.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(549, 590)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_15 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_15.setGeometry(QtCore.QRect(350, 60, 191, 491))
        self.groupBox_15.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_15.setObjectName("groupBox_15")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget_3 = QtWidgets.QListWidget(self.groupBox_15)
        self.listWidget_3.setMaximumSize(QtCore.QSize(16777215, 19))
        self.listWidget_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_3.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.listWidget_3.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.listWidget_3.setFlow(QtWidgets.QListView.LeftToRight)
        self.listWidget_3.setProperty("isWrapping", False)
        self.listWidget_3.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_3.setModelColumn(0)
        self.listWidget_3.setObjectName("listWidget_3")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        self.verticalLayout.addWidget(self.listWidget_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_11 = QtWidgets.QLabel(self.groupBox_15)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 8, 0, 1, 1)
        self.spinBox_10 = QtWidgets.QSpinBox(self.groupBox_15)
        self.spinBox_10.setObjectName("spinBox_10")
        self.gridLayout.addWidget(self.spinBox_10, 7, 1, 1, 1)
        self.spinBox_11 = QtWidgets.QSpinBox(self.groupBox_15)
        self.spinBox_11.setObjectName("spinBox_11")
        self.gridLayout.addWidget(self.spinBox_11, 8, 1, 1, 1)
        self.spinBox_7 = QtWidgets.QSpinBox(self.groupBox_15)
        self.spinBox_7.setObjectName("spinBox_7")
        self.gridLayout.addWidget(self.spinBox_7, 5, 1, 1, 1)
        self.spinBox_12 = QtWidgets.QSpinBox(self.groupBox_15)
        self.spinBox_12.setObjectName("spinBox_12")
        self.gridLayout.addWidget(self.spinBox_12, 2, 1, 1, 1)
        self.spinBox_8 = QtWidgets.QSpinBox(self.groupBox_15)
        self.spinBox_8.setObjectName("spinBox_8")
        self.gridLayout.addWidget(self.spinBox_8, 4, 1, 1, 1)
        self.spinBox_9 = QtWidgets.QSpinBox(self.groupBox_15)
        self.spinBox_9.setObjectName("spinBox_9")
        self.gridLayout.addWidget(self.spinBox_9, 3, 1, 1, 1)
        self.spinBox_6 = QtWidgets.QSpinBox(self.groupBox_15)
        self.spinBox_6.setObjectName("spinBox_6")
        self.gridLayout.addWidget(self.spinBox_6, 6, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_15)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_15)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 7, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_15)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 13, 0, 1, 1)
        self.spinBox_3 = QtWidgets.QSpinBox(self.groupBox_15)
        self.spinBox_3.setObjectName("spinBox_3")
        self.gridLayout.addWidget(self.spinBox_3, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_15)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_15)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_15)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 14, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_15)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 0, 1, 1, 1)
        self.spinBox_4 = QtWidgets.QSpinBox(self.groupBox_15)
        self.spinBox_4.setObjectName("spinBox_4")
        self.gridLayout.addWidget(self.spinBox_4, 9, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_15)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 10, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_15)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_15)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.spinBox_5 = QtWidgets.QSpinBox(self.groupBox_15)
        self.spinBox_5.setObjectName("spinBox_5")
        self.gridLayout.addWidget(self.spinBox_5, 10, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_15)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 6, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_15)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 12, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_15)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 11, 0, 1, 1)
        self.spinBox_13 = QtWidgets.QSpinBox(self.groupBox_15)
        self.spinBox_13.setObjectName("spinBox_13")
        self.gridLayout.addWidget(self.spinBox_13, 11, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_15)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 9, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_15)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_15)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 15, 0, 1, 1)
        self.spinBox_14 = QtWidgets.QSpinBox(self.groupBox_15)
        self.spinBox_14.setObjectName("spinBox_14")
        self.gridLayout.addWidget(self.spinBox_14, 12, 1, 1, 1)
        self.spinBox_15 = QtWidgets.QSpinBox(self.groupBox_15)
        self.spinBox_15.setObjectName("spinBox_15")
        self.gridLayout.addWidget(self.spinBox_15, 13, 1, 1, 1)
        self.spinBox_16 = QtWidgets.QSpinBox(self.groupBox_15)
        self.spinBox_16.setObjectName("spinBox_16")
        self.gridLayout.addWidget(self.spinBox_16, 14, 1, 1, 1)
        self.spinBox_17 = QtWidgets.QSpinBox(self.groupBox_15)
        self.spinBox_17.setObjectName("spinBox_17")
        self.gridLayout.addWidget(self.spinBox_17, 15, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(200, 100, 101, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_123 = QtWidgets.QLabel(self.centralwidget)
        self.label_123.setGeometry(QtCore.QRect(140, 100, 47, 13))
        self.label_123.setObjectName("label_123")
        self.groupBox_14 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_14.setGeometry(QtCore.QRect(130, 130, 179, 131))
        self.groupBox_14.setObjectName("groupBox_14")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.groupBox_14)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.label_197 = QtWidgets.QLabel(self.groupBox_14)
        self.label_197.setObjectName("label_197")
        self.gridLayout_30.addWidget(self.label_197, 0, 0, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_14)
        self.doubleSpinBox.setDecimals(1)
        self.doubleSpinBox.setMinimum(0.5)
        self.doubleSpinBox.setMaximum(1.5)
        self.doubleSpinBox.setSingleStep(0.1)
        self.doubleSpinBox.setProperty("value", 1.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout_30.addWidget(self.doubleSpinBox, 0, 1, 1, 1)
        self.label_198 = QtWidgets.QLabel(self.groupBox_14)
        self.label_198.setObjectName("label_198")
        self.gridLayout_30.addWidget(self.label_198, 1, 0, 1, 1)
        self.label_199 = QtWidgets.QLabel(self.groupBox_14)
        self.label_199.setObjectName("label_199")
        self.gridLayout_30.addWidget(self.label_199, 2, 0, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox_14)
        self.spinBox_2.setMaximum(5)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout_30.addWidget(self.spinBox_2, 2, 1, 1, 1)
        self.label_200 = QtWidgets.QLabel(self.groupBox_14)
        self.label_200.setObjectName("label_200")
        self.gridLayout_30.addWidget(self.label_200, 3, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_14)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_30.addWidget(self.comboBox, 3, 1, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_14)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout_30.addWidget(self.comboBox_2, 1, 1, 1, 1)
        self.TroopCfgDescriptions = QtWidgets.QGroupBox(self.centralwidget)
        self.TroopCfgDescriptions.setGeometry(QtCore.QRect(10, 290, 301, 268))
        self.TroopCfgDescriptions.setAlignment(QtCore.Qt.AlignCenter)
        self.TroopCfgDescriptions.setObjectName("TroopCfgDescriptions")
        self.Descriptions_2 = QtWidgets.QStackedWidget(self.TroopCfgDescriptions)
        self.Descriptions_2.setGeometry(QtCore.QRect(0, 38, 301, 231))
        self.Descriptions_2.setObjectName("Descriptions_2")
        self.DescriptionsPage1_2 = QtWidgets.QWidget()
        self.DescriptionsPage1_2.setObjectName("DescriptionsPage1_2")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.DescriptionsPage1_2)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.German_3 = QtWidgets.QPlainTextEdit(self.DescriptionsPage1_2)
        self.German_3.setObjectName("German_3")
        self.gridLayout_24.addWidget(self.German_3, 0, 0, 1, 1)
        self.Descriptions_2.addWidget(self.DescriptionsPage1_2)
        self.DescriptionsPage2_2 = QtWidgets.QWidget()
        self.DescriptionsPage2_2.setObjectName("DescriptionsPage2_2")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.DescriptionsPage2_2)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.English_3 = QtWidgets.QPlainTextEdit(self.DescriptionsPage2_2)
        self.English_3.setObjectName("English_3")
        self.gridLayout_25.addWidget(self.English_3, 0, 0, 1, 1)
        self.Descriptions_2.addWidget(self.DescriptionsPage2_2)
        self.DescriptionsPage3_2 = QtWidgets.QWidget()
        self.DescriptionsPage3_2.setObjectName("DescriptionsPage3_2")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.DescriptionsPage3_2)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.Polish_3 = QtWidgets.QPlainTextEdit(self.DescriptionsPage3_2)
        self.Polish_3.setObjectName("Polish_3")
        self.gridLayout_26.addWidget(self.Polish_3, 0, 0, 1, 1)
        self.Descriptions_2.addWidget(self.DescriptionsPage3_2)
        self.DescriptionsPage4_2 = QtWidgets.QWidget()
        self.DescriptionsPage4_2.setObjectName("DescriptionsPage4_2")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.DescriptionsPage4_2)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.Russian_3 = QtWidgets.QPlainTextEdit(self.DescriptionsPage4_2)
        self.Russian_3.setObjectName("Russian_3")
        self.gridLayout_27.addWidget(self.Russian_3, 0, 0, 1, 1)
        self.Descriptions_2.addWidget(self.DescriptionsPage4_2)
        self.DescriptionsPage5_2 = QtWidgets.QWidget()
        self.DescriptionsPage5_2.setObjectName("DescriptionsPage5_2")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.DescriptionsPage5_2)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.Chinese_3 = QtWidgets.QPlainTextEdit(self.DescriptionsPage5_2)
        self.Chinese_3.setObjectName("Chinese_3")
        self.gridLayout_28.addWidget(self.Chinese_3, 0, 0, 1, 1)
        self.Descriptions_2.addWidget(self.DescriptionsPage5_2)
        self.DescriptionsPage6_2 = QtWidgets.QWidget()
        self.DescriptionsPage6_2.setObjectName("DescriptionsPage6_2")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.DescriptionsPage6_2)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.Hungarian_3 = QtWidgets.QPlainTextEdit(self.DescriptionsPage6_2)
        self.Hungarian_3.setObjectName("Hungarian_3")
        self.gridLayout_29.addWidget(self.Hungarian_3, 0, 0, 1, 1)
        self.Descriptions_2.addWidget(self.DescriptionsPage6_2)
        self.listWidget_2 = QtWidgets.QListWidget(self.TroopCfgDescriptions)
        self.listWidget_2.setGeometry(QtCore.QRect(10, 20, 281, 19))
        self.listWidget_2.setMaximumSize(QtCore.QSize(16777215, 19))
        self.listWidget_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.listWidget_2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.listWidget_2.setFlow(QtWidgets.QListView.LeftToRight)
        self.listWidget_2.setProperty("isWrapping", False)
        self.listWidget_2.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_2.setModelColumn(0)
        self.listWidget_2.setObjectName("listWidget_2")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 549, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.listWidget_3.setCurrentRow(-1)
        self.Descriptions_2.setCurrentIndex(0)
        self.listWidget_2.setCurrentRow(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Troop Config Editor - UCPREGUI"))
        self.groupBox_15.setTitle(_translate("MainWindow", "Troops"))
        __sortingEnabled = self.listWidget_3.isSortingEnabled()
        self.listWidget_3.setSortingEnabled(False)
        item = self.listWidget_3.item(0)
        item.setText(_translate("MainWindow", "Normal"))
        item = self.listWidget_3.item(1)
        item.setText(_translate("MainWindow", "Crusader"))
        item = self.listWidget_3.item(2)
        item.setText(_translate("MainWindow", "Deathmatch"))
        self.listWidget_3.setSortingEnabled(__sortingEnabled)
        self.label_11.setText(_translate("MainWindow", "TextLabel"))
        self.label_7.setText(_translate("MainWindow", "TextLabel"))
        self.label_10.setText(_translate("MainWindow", "TextLabel"))
        self.label_14.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_15.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.label_9.setText(_translate("MainWindow", "TextLabel"))
        self.label_13.setText(_translate("MainWindow", "TextLabel"))
        self.label_12.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_8.setText(_translate("MainWindow", "TextLabel"))
        self.label_16.setText(_translate("MainWindow", "TextLabel"))
        self.label_123.setText(_translate("MainWindow", "Name"))
        self.groupBox_14.setTitle(_translate("MainWindow", "Lord"))
        self.label_197.setText(_translate("MainWindow", "StrengthMultiplier"))
        self.label_198.setText(_translate("MainWindow", "DotColour"))
        self.label_199.setText(_translate("MainWindow", "DotCount"))
        self.label_200.setText(_translate("MainWindow", "Type"))
        self.TroopCfgDescriptions.setTitle(_translate("MainWindow", "Troop Config File Description"))
        self.German_3.setPlaceholderText(_translate("MainWindow", "Description"))
        self.English_3.setPlaceholderText(_translate("MainWindow", "Description"))
        self.Polish_3.setPlaceholderText(_translate("MainWindow", "Description"))
        self.Russian_3.setPlaceholderText(_translate("MainWindow", "Description"))
        self.Chinese_3.setPlaceholderText(_translate("MainWindow", "Description"))
        self.Hungarian_3.setPlaceholderText(_translate("MainWindow", "Description"))
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        item = self.listWidget_2.item(0)
        item.setText(_translate("MainWindow", "German"))
        item = self.listWidget_2.item(1)
        item.setText(_translate("MainWindow", "English"))
        item = self.listWidget_2.item(2)
        item.setText(_translate("MainWindow", "Polish"))
        item = self.listWidget_2.item(3)
        item.setText(_translate("MainWindow", "Russian"))
        item = self.listWidget_2.item(4)
        item.setText(_translate("MainWindow", "Chinese"))
        item = self.listWidget_2.item(5)
        item.setText(_translate("MainWindow", "Hungarian"))
        self.listWidget_2.setSortingEnabled(__sortingEnabled)
