# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trped_mw.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(499, 543)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_15 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_15.setGeometry(QtCore.QRect(310, 70, 171, 451))
        self.groupBox_15.setTitle("")
        self.groupBox_15.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_15.setObjectName("groupBox_15")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_15)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 141, 431))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 8, 0, 1, 1)
        self.ArabArcher = QtWidgets.QSpinBox(self.layoutWidget)
        self.ArabArcher.setMaximum(4096)
        self.ArabArcher.setObjectName("ArabArcher")
        self.gridLayout.addWidget(self.ArabArcher, 7, 1, 1, 1)
        self.Slave = QtWidgets.QSpinBox(self.layoutWidget)
        self.Slave.setMaximum(4096)
        self.Slave.setObjectName("Slave")
        self.gridLayout.addWidget(self.Slave, 8, 1, 1, 1)
        self.Swordsman = QtWidgets.QSpinBox(self.layoutWidget)
        self.Swordsman.setMaximum(4096)
        self.Swordsman.setObjectName("Swordsman")
        self.gridLayout.addWidget(self.Swordsman, 5, 1, 1, 1)
        self.Maceman = QtWidgets.QSpinBox(self.layoutWidget)
        self.Maceman.setMaximum(4096)
        self.Maceman.setObjectName("Maceman")
        self.gridLayout.addWidget(self.Maceman, 2, 1, 1, 1)
        self.Pikeman = QtWidgets.QSpinBox(self.layoutWidget)
        self.Pikeman.setMaximum(4096)
        self.Pikeman.setObjectName("Pikeman")
        self.gridLayout.addWidget(self.Pikeman, 4, 1, 1, 1)
        self.Crossbowman = QtWidgets.QSpinBox(self.layoutWidget)
        self.Crossbowman.setMaximum(4096)
        self.Crossbowman.setObjectName("Crossbowman")
        self.gridLayout.addWidget(self.Crossbowman, 3, 1, 1, 1)
        self.Knight = QtWidgets.QSpinBox(self.layoutWidget)
        self.Knight.setMaximum(4096)
        self.Knight.setObjectName("Knight")
        self.gridLayout.addWidget(self.Knight, 6, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 7, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 13, 0, 1, 1)
        self.Spearman = QtWidgets.QSpinBox(self.layoutWidget)
        self.Spearman.setMaximum(4096)
        self.Spearman.setObjectName("Spearman")
        self.gridLayout.addWidget(self.Spearman, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 14, 0, 1, 1)
        self.EuropArcher = QtWidgets.QSpinBox(self.layoutWidget)
        self.EuropArcher.setMaximum(4096)
        self.EuropArcher.setObjectName("EuropArcher")
        self.gridLayout.addWidget(self.EuropArcher, 0, 1, 1, 1)
        self.Slinger = QtWidgets.QSpinBox(self.layoutWidget)
        self.Slinger.setMaximum(4096)
        self.Slinger.setObjectName("Slinger")
        self.gridLayout.addWidget(self.Slinger, 9, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 10, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.Assassin = QtWidgets.QSpinBox(self.layoutWidget)
        self.Assassin.setMaximum(4096)
        self.Assassin.setObjectName("Assassin")
        self.gridLayout.addWidget(self.Assassin, 10, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 6, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 12, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 11, 0, 1, 1)
        self.HorseArcher = QtWidgets.QSpinBox(self.layoutWidget)
        self.HorseArcher.setMaximum(4096)
        self.HorseArcher.setObjectName("HorseArcher")
        self.gridLayout.addWidget(self.HorseArcher, 11, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 9, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        self.label_16.setEnabled(False)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 15, 0, 1, 1)
        self.ArabSwordsman = QtWidgets.QSpinBox(self.layoutWidget)
        self.ArabSwordsman.setMaximum(4096)
        self.ArabSwordsman.setObjectName("ArabSwordsman")
        self.gridLayout.addWidget(self.ArabSwordsman, 12, 1, 1, 1)
        self.FireThrower = QtWidgets.QSpinBox(self.layoutWidget)
        self.FireThrower.setMaximum(4096)
        self.FireThrower.setObjectName("FireThrower")
        self.gridLayout.addWidget(self.FireThrower, 13, 1, 1, 1)
        self.Monk = QtWidgets.QSpinBox(self.layoutWidget)
        self.Monk.setMaximum(4096)
        self.Monk.setObjectName("Monk")
        self.gridLayout.addWidget(self.Monk, 14, 1, 1, 1)
        self.Tunneller = QtWidgets.QSpinBox(self.layoutWidget)
        self.Tunneller.setEnabled(False)
        self.Tunneller.setMaximum(4096)
        self.Tunneller.setObjectName("Tunneller")
        self.gridLayout.addWidget(self.Tunneller, 15, 1, 1, 1)
        self.TroopCfgDescriptions = QtWidgets.QGroupBox(self.centralwidget)
        self.TroopCfgDescriptions.setGeometry(QtCore.QRect(0, 260, 301, 268))
        self.TroopCfgDescriptions.setAlignment(QtCore.Qt.AlignCenter)
        self.TroopCfgDescriptions.setObjectName("TroopCfgDescriptions")
        self.descr_tab = QtWidgets.QTabWidget(self.TroopCfgDescriptions)
        self.descr_tab.setGeometry(QtCore.QRect(0, 20, 301, 241))
        self.descr_tab.setObjectName("descr_tab")
        self.German = QtWidgets.QWidget()
        self.German.setObjectName("German")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.German)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.German_3 = QtWidgets.QPlainTextEdit(self.German)
        self.German_3.setObjectName("German_3")
        self.gridLayout_24.addWidget(self.German_3, 0, 0, 1, 1)
        self.descr_tab.addTab(self.German, "")
        self.English = QtWidgets.QWidget()
        self.English.setObjectName("English")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.English)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.English_3 = QtWidgets.QPlainTextEdit(self.English)
        self.English_3.setObjectName("English_3")
        self.gridLayout_25.addWidget(self.English_3, 0, 0, 1, 1)
        self.descr_tab.addTab(self.English, "")
        self.Polish = QtWidgets.QWidget()
        self.Polish.setObjectName("Polish")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.Polish)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.Polish_3 = QtWidgets.QPlainTextEdit(self.Polish)
        self.Polish_3.setObjectName("Polish_3")
        self.gridLayout_26.addWidget(self.Polish_3, 0, 0, 1, 1)
        self.descr_tab.addTab(self.Polish, "")
        self.Russian = QtWidgets.QWidget()
        self.Russian.setObjectName("Russian")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.Russian)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.Russian_3 = QtWidgets.QPlainTextEdit(self.Russian)
        self.Russian_3.setObjectName("Russian_3")
        self.gridLayout_27.addWidget(self.Russian_3, 0, 0, 1, 1)
        self.descr_tab.addTab(self.Russian, "")
        self.Chinese = QtWidgets.QWidget()
        self.Chinese.setObjectName("Chinese")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.Chinese)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.Chinese_3 = QtWidgets.QPlainTextEdit(self.Chinese)
        self.Chinese_3.setObjectName("Chinese_3")
        self.gridLayout_28.addWidget(self.Chinese_3, 0, 0, 1, 1)
        self.descr_tab.addTab(self.Chinese, "")
        self.Hungarian = QtWidgets.QWidget()
        self.Hungarian.setObjectName("Hungarian")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.Hungarian)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.Hungarian_3 = QtWidgets.QPlainTextEdit(self.Hungarian)
        self.Hungarian_3.setObjectName("Hungarian_3")
        self.gridLayout_29.addWidget(self.Hungarian_3, 0, 0, 1, 1)
        self.descr_tab.addTab(self.Hungarian, "")
        self.Lord_Tab = QtWidgets.QTabWidget(self.centralwidget)
        self.Lord_Tab.setGeometry(QtCore.QRect(0, 10, 491, 21))
        self.Lord_Tab.setObjectName("Lord_Tab")
        self.Rat = QtWidgets.QWidget()
        self.Rat.setObjectName("Rat")
        self.Lord_Tab.addTab(self.Rat, "")
        self.Snake = QtWidgets.QWidget()
        self.Snake.setObjectName("Snake")
        self.Lord_Tab.addTab(self.Snake, "")
        self.Pig = QtWidgets.QWidget()
        self.Pig.setObjectName("Pig")
        self.Lord_Tab.addTab(self.Pig, "")
        self.Wolf = QtWidgets.QWidget()
        self.Wolf.setObjectName("Wolf")
        self.Lord_Tab.addTab(self.Wolf, "")
        self.Saladin = QtWidgets.QWidget()
        self.Saladin.setObjectName("Saladin")
        self.Lord_Tab.addTab(self.Saladin, "")
        self.Caliph = QtWidgets.QWidget()
        self.Caliph.setObjectName("Caliph")
        self.Lord_Tab.addTab(self.Caliph, "")
        self.Sultan = QtWidgets.QWidget()
        self.Sultan.setObjectName("Sultan")
        self.Lord_Tab.addTab(self.Sultan, "")
        self.Richard = QtWidgets.QWidget()
        self.Richard.setObjectName("Richard")
        self.Lord_Tab.addTab(self.Richard, "")
        self.Frederick = QtWidgets.QWidget()
        self.Frederick.setObjectName("Frederick")
        self.Lord_Tab.addTab(self.Frederick, "")
        self.Phillip = QtWidgets.QWidget()
        self.Phillip.setObjectName("Phillip")
        self.Lord_Tab.addTab(self.Phillip, "")
        self.Wazir = QtWidgets.QWidget()
        self.Wazir.setObjectName("Wazir")
        self.Lord_Tab.addTab(self.Wazir, "")
        self.Emir = QtWidgets.QWidget()
        self.Emir.setObjectName("Emir")
        self.Lord_Tab.addTab(self.Emir, "")
        self.Nizar = QtWidgets.QWidget()
        self.Nizar.setObjectName("Nizar")
        self.Lord_Tab.addTab(self.Nizar, "")
        self.Sheriff = QtWidgets.QWidget()
        self.Sheriff.setObjectName("Sheriff")
        self.Lord_Tab.addTab(self.Sheriff, "")
        self.Marshall = QtWidgets.QWidget()
        self.Marshall.setObjectName("Marshall")
        self.Lord_Tab.addTab(self.Marshall, "")
        self.Abbot = QtWidgets.QWidget()
        self.Abbot.setObjectName("Abbot")
        self.Lord_Tab.addTab(self.Abbot, "")
        self.Player_eu = QtWidgets.QWidget()
        self.Player_eu.setObjectName("Player_eu")
        self.Lord_Tab.addTab(self.Player_eu, "")
        self.Player_ar = QtWidgets.QWidget()
        self.Player_ar.setObjectName("Player_ar")
        self.Lord_Tab.addTab(self.Player_ar, "")
        self.mode_tab = QtWidgets.QTabWidget(self.centralwidget)
        self.mode_tab.setGeometry(QtCore.QRect(290, 40, 201, 21))
        self.mode_tab.setUsesScrollButtons(False)
        self.mode_tab.setObjectName("mode_tab")
        self.Normal = QtWidgets.QWidget()
        self.Normal.setObjectName("Normal")
        self.mode_tab.addTab(self.Normal, "")
        self.Crusader = QtWidgets.QWidget()
        self.Crusader.setObjectName("Crusader")
        self.mode_tab.addTab(self.Crusader, "")
        self.Deathmatch = QtWidgets.QWidget()
        self.Deathmatch.setObjectName("Deathmatch")
        self.mode_tab.addTab(self.Deathmatch, "")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setGeometry(QtCore.QRect(70, 80, 179, 151))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label_123 = QtWidgets.QLabel(self.splitter)
        self.label_123.setObjectName("label_123")
        self.Name = QtWidgets.QLineEdit(self.splitter)
        self.Name.setObjectName("Name")
        self.Lord = QtWidgets.QGroupBox(self.splitter_2)
        self.Lord.setObjectName("Lord")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.Lord)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.label_197 = QtWidgets.QLabel(self.Lord)
        self.label_197.setObjectName("label_197")
        self.gridLayout_30.addWidget(self.label_197, 0, 0, 1, 1)
        self.StrengthMultiplier = QtWidgets.QDoubleSpinBox(self.Lord)
        self.StrengthMultiplier.setDecimals(1)
        self.StrengthMultiplier.setMinimum(0.5)
        self.StrengthMultiplier.setMaximum(1.5)
        self.StrengthMultiplier.setSingleStep(0.1)
        self.StrengthMultiplier.setProperty("value", 1.0)
        self.StrengthMultiplier.setObjectName("StrengthMultiplier")
        self.gridLayout_30.addWidget(self.StrengthMultiplier, 0, 1, 1, 1)
        self.label_198 = QtWidgets.QLabel(self.Lord)
        self.label_198.setObjectName("label_198")
        self.gridLayout_30.addWidget(self.label_198, 1, 0, 1, 1)
        self.label_199 = QtWidgets.QLabel(self.Lord)
        self.label_199.setObjectName("label_199")
        self.gridLayout_30.addWidget(self.label_199, 2, 0, 1, 1)
        self.DotCount = QtWidgets.QSpinBox(self.Lord)
        self.DotCount.setMaximum(5)
        self.DotCount.setObjectName("DotCount")
        self.gridLayout_30.addWidget(self.DotCount, 2, 1, 1, 1)
        self.label_200 = QtWidgets.QLabel(self.Lord)
        self.label_200.setObjectName("label_200")
        self.gridLayout_30.addWidget(self.label_200, 3, 0, 1, 1)
        self.Type = QtWidgets.QComboBox(self.Lord)
        self.Type.setObjectName("Type")
        self.Type.addItem("")
        self.Type.addItem("")
        self.gridLayout_30.addWidget(self.Type, 3, 1, 1, 1)
        self.DotColour = QtWidgets.QComboBox(self.Lord)
        self.DotColour.setObjectName("DotColour")
        self.DotColour.addItem("")
        self.DotColour.addItem("")
        self.gridLayout_30.addWidget(self.DotColour, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 499, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.descr_tab.setCurrentIndex(0)
        self.Lord_Tab.setCurrentIndex(0)
        self.mode_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Troop Config Editor - UCPREGUI"))
        self.label_11.setText(_translate("MainWindow", "Slave"))
        self.label_7.setText(_translate("MainWindow", "Crossbowman"))
        self.label_10.setText(_translate("MainWindow", "ArabArcher"))
        self.label_14.setText(_translate("MainWindow", "FireThrower"))
        self.label.setText(_translate("MainWindow", "EuropArcher"))
        self.label_2.setText(_translate("MainWindow", "Spearman"))
        self.label_15.setText(_translate("MainWindow", "Monk"))
        self.label_4.setText(_translate("MainWindow", "Assassin"))
        self.label_5.setText(_translate("MainWindow", "Swordsman"))
        self.label_6.setText(_translate("MainWindow", "Pikeman"))
        self.label_9.setText(_translate("MainWindow", "Knight"))
        self.label_13.setText(_translate("MainWindow", "ArabSwordsman"))
        self.label_12.setText(_translate("MainWindow", "HorseArcher"))
        self.label_3.setText(_translate("MainWindow", "Slinger"))
        self.label_8.setText(_translate("MainWindow", "Maceman"))
        self.label_16.setText(_translate("MainWindow", "Tunneller"))
        self.TroopCfgDescriptions.setTitle(_translate("MainWindow", "Troop Config File Description"))
        self.German_3.setPlaceholderText(_translate("MainWindow", "Description"))
        self.descr_tab.setTabText(self.descr_tab.indexOf(self.German), _translate("MainWindow", "German"))
        self.English_3.setPlaceholderText(_translate("MainWindow", "Description"))
        self.descr_tab.setTabText(self.descr_tab.indexOf(self.English), _translate("MainWindow", "English"))
        self.Polish_3.setPlaceholderText(_translate("MainWindow", "Description"))
        self.descr_tab.setTabText(self.descr_tab.indexOf(self.Polish), _translate("MainWindow", "Polish"))
        self.Russian_3.setPlaceholderText(_translate("MainWindow", "Description"))
        self.descr_tab.setTabText(self.descr_tab.indexOf(self.Russian), _translate("MainWindow", "Russian"))
        self.Chinese_3.setPlaceholderText(_translate("MainWindow", "Description"))
        self.descr_tab.setTabText(self.descr_tab.indexOf(self.Chinese), _translate("MainWindow", "Chinese"))
        self.Hungarian_3.setPlaceholderText(_translate("MainWindow", "Description"))
        self.descr_tab.setTabText(self.descr_tab.indexOf(self.Hungarian), _translate("MainWindow", "Hungarian"))
        self.Lord_Tab.setTabText(self.Lord_Tab.indexOf(self.Rat), _translate("MainWindow", "Rat"))
        self.Lord_Tab.setTabText(self.Lord_Tab.indexOf(self.Snake), _translate("MainWindow", "Snake"))
        self.Lord_Tab.setTabText(self.Lord_Tab.indexOf(self.Pig), _translate("MainWindow", "Pig"))
        self.Lord_Tab.setTabText(self.Lord_Tab.indexOf(self.Wolf), _translate("MainWindow", "Wolf"))
        self.Lord_Tab.setTabText(self.Lord_Tab.indexOf(self.Saladin), _translate("MainWindow", "Saladin"))
        self.Lord_Tab.setTabText(self.Lord_Tab.indexOf(self.Caliph), _translate("MainWindow", "Caliph"))
        self.Lord_Tab.setTabText(self.Lord_Tab.indexOf(self.Sultan), _translate("MainWindow", "Sultan"))
        self.Lord_Tab.setTabText(self.Lord_Tab.indexOf(self.Richard), _translate("MainWindow", "Richard"))
        self.Lord_Tab.setTabText(self.Lord_Tab.indexOf(self.Frederick), _translate("MainWindow", "Frederick"))
        self.Lord_Tab.setTabText(self.Lord_Tab.indexOf(self.Phillip), _translate("MainWindow", "Phillip"))
        self.Lord_Tab.setTabText(self.Lord_Tab.indexOf(self.Wazir), _translate("MainWindow", "Wazir"))
        self.Lord_Tab.setTabText(self.Lord_Tab.indexOf(self.Emir), _translate("MainWindow", "Emir"))
        self.Lord_Tab.setTabText(self.Lord_Tab.indexOf(self.Nizar), _translate("MainWindow", "Nizar"))
        self.Lord_Tab.setTabText(self.Lord_Tab.indexOf(self.Sheriff), _translate("MainWindow", "Sheriff"))
        self.Lord_Tab.setTabText(self.Lord_Tab.indexOf(self.Marshall), _translate("MainWindow", "Marshall"))
        self.Lord_Tab.setTabText(self.Lord_Tab.indexOf(self.Abbot), _translate("MainWindow", "Abbot"))
        self.Lord_Tab.setTabText(self.Lord_Tab.indexOf(self.Player_eu), _translate("MainWindow", "Player-European"))
        self.Lord_Tab.setTabText(self.Lord_Tab.indexOf(self.Player_ar), _translate("MainWindow", "Player-Arab"))
        self.mode_tab.setTabText(self.mode_tab.indexOf(self.Normal), _translate("MainWindow", "Normal"))
        self.mode_tab.setTabText(self.mode_tab.indexOf(self.Crusader), _translate("MainWindow", "Crusader"))
        self.mode_tab.setTabText(self.mode_tab.indexOf(self.Deathmatch), _translate("MainWindow", "Deathmatch"))
        self.label_123.setText(_translate("MainWindow", "Name"))
        self.Lord.setTitle(_translate("MainWindow", "Lord"))
        self.label_197.setText(_translate("MainWindow", "StrengthMultiplier"))
        self.label_198.setText(_translate("MainWindow", "DotColour"))
        self.label_199.setText(_translate("MainWindow", "DotCount"))
        self.label_200.setText(_translate("MainWindow", "Type"))
        self.Type.setItemText(0, _translate("MainWindow", "Europ"))
        self.Type.setItemText(1, _translate("MainWindow", "Arab"))
        self.DotColour.setItemText(0, _translate("MainWindow", "Yellow"))
        self.DotColour.setItemText(1, _translate("MainWindow", "Blue"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
